baseURL = 'https://liongma.com/'


locale = 'en-us'
title = 'Liong Ma'
theme = "PaperMod"

[params]
  mainSections = ["projects"]
  comments = true
  
[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Gallery"
    url = "/artwork/"
    weight = 3


  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


